---
title: "Final Project"
author: "Miroslav Bergam"
date: "10/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(ggplot2)
library(formattable)

##  People who donated to more than one
## PS8 data source

## Ideology scores
## Boxplots to show amounts 
### Sankey chart: left hand side is schools,right hand side is candidates
### something inferential // statistical modelling
    # take the individual donations as  one datapoint,  and take amount as a function of ideology
    # include polynomials to do curves  amt ~ ideology + ideology ^2... or add a cubed

```

```{r Data Cleaning}

data <- read_csv("presdonors.csv") %>%
  select(committee_name, contributor_name, 
         contributor_employer, 
         contributor_occupation, 
         contributor_first_name, 
         contributor_last_name, 
         contribution_receipt_amount, 
         contribution_receipt_date) %>%
  filter(committee_name != "") %>%
  filter(contributor_occupation != "STUDENT") %>%
  filter(contributor_occupation != "GRADUATE STUDENT") %>%
  filter(contributor_employer != "HARVARD-WESTLAKE SCHOOL") %>%
  filter(contributor_employer != "HARVARD VANGUARD") %>%
  filter(contributor_employer != "HARVARD VANGUARD MEDICAL ASSOCIATES") %>%
  filter(contributor_employer != "HARVARD VANGUARD HEALTH ED") %>%
  filter(contributor_employer != "HARVARD-EPWORTH UMC") %>%
  filter(contributor_employer != "HARVARD HOSPITAL") %>%
  filter(committee_name != "DEMOCRATS WORK FOR AMERICA, INC") %>%
  filter(committee_name != "BLACK PAC") %>%
  filter(committee_name != "FORWARD MAJORITY ACTION") %>%
  filter(committee_name != "MIND THE GAP") %>%
  filter(committee_name != "NEED TO IMPEACH") %>%
  filter(committee_name != "UNITE AMERICA CONGRESSIONAL ELECTION FUND") %>%
  filter(committee_name != "WYOMING STRONG ACTION") %>%
  filter(committee_name != "LCV VICTORY FUND") %>%
  filter(committee_name != "WITH HONOR FUND, INC.") %>%
  filter(committee_name != "JOE SESTAK FOR PRESIDENT") %>%
  filter(committee_name != "SMP") %>%
  filter(committee_name != "HOUSE MAJORITY PAC") %>%
  mutate(committee_name=dplyr::recode(committee_name,
                `AMY FOR AMERICA` = "Amy Klobuchar",
                `BENNET FOR AMERICA` = "Michael Bennet",
                `BERNIE 2020` = "Bernie Sanders",
                `BETO FOR AMERICA` = "Beto O'Rourke",
                `BIDEN FOR PRESIDENT` = "Joe Biden",
                `BULLOCK FOR PRESIDENT` = "Steve Bullock",
                `CORY 2020` = "Cory Booker",
                `DONALD J. TRUMP FOR PRESIDENT, INC.` = "Donald Trump",
                `FRIENDS OF ANDREW YANG` = "Andrew Yang",
                `FRIENDS OF JOHN DELANEY` = "John Delaney",
                `GILLIBRAND 2020` = "Kirstan Gillibrand",
                `HICKENLOOPER 2020` = "John Hickenlooper",
                `INSLEE FOR AMERICA` = "Jay Inslee",
                `JULIAN FOR THE FUTURE` = "Julian Castro",
                `KAMALA HARRIS FOR THE PEOPLE` = "Kamala Harris",
                `PETE FOR AMERICA, INC.` = "Pete Buttigieg",
                `SETH MOULTON FOR AMERICA, INC.` = "Seth Moulton",
                `SWALWELL FOR AMERICA` = "Eric Swalwell",
                `TOM STEYER 2020` = "Tom Steyer",
                `TULSI NOW` = "Tulsi Gabbard",
                `WARREN FOR PRESIDENT, INC.` = "Elizabeth Warren",
                `WALSH FOR PRESIDENT` = "Joe Walsh",
                `WELD 2020 PRESIDENTIAL CAMPAIGN COMMITTEE, INC.` = "Bill Weld"))
  

pres <- read_csv("pres.csv") %>%
  mutate(name=dplyr::recode(name,
                `KLOBUCHAR, AMY J.` = "Amy Klobuchar",
                `BENNET, MICHAEL F.` = "Michael Bennet",
                `SANDERS, BERNARD` = "Bernie Sanders",
                `O'ROURKE, ROBERT BETO` = "Beto O'Rourke",
                `BIDEN, JOSEPH R JR` = "Joe Biden",
                `BULLOCK, STEVE` = "Steve Bullock",
                `BOOKER, CORY A.` = "Cory Booker",
                `TRUMP, DONALD J.` = "Donald Trump",
                `YANG, ANDREW MR.` = "Andrew Yang",
                `DELANEY, JOHN K.` = "John Delaney",
                `GILLIBRAND, KIRSTEN` = "Kirstan Gillibrand",
                `HICKENLOOPER, JOHN W.` = "John Hickenlooper",
                `INSLEE, JAY R` = "Jay Inslee",
                `CASTRO, JULIAN` = "Julian Castro",
                `HARRIS, KAMALA D.` = "Kamala Harris",
                `BUTTIGIEG, PETE` = "Pete Buttigieg",
                `MOULTON, SETH` = "Seth Moulton",
                `SWALWELL, ERIC MICHAEL` = "Eric Swalwell",
                `STEYER, TOM` = "Tom Steyer",
                `GABBARD, TULSI` = "Tulsi Gabbard",
                `WARREN, ELIZABETH` = "Elizabeth Warren",
                `WALSH, JOE` = "Joe Walsh",
                `WELD, WILLIAM FLOYD (BILL)` = "Bill Weld")) %>%
  select(name, party_full, receipts)

data <- data %>%
  left_join(pres, by = c("committee_name" = "name"))

ideologies <- read_csv("ideology_score.csv") %>%
  select(Name, estimate)

data <- data %>%
  left_join(ideologies, by = c("committee_name" = "Name"))

```

```{r PROF ONLY}

profs <- data %>%
  filter(contributor_occupation == "PROFESSOR")

############################

number_donations <- profs %>%
  group_by(committee_name) %>%
  summarise(num_donations = n()) %>%
  mutate(num_donations = as.numeric(num_donations))


ggplot(number_donations, aes(x = reorder(committee_name, num_donations), y = num_donations, fill = committee_name)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") + 
  labs(title = "Harvard Professors' Political Donations to 2020 Presidential Campaigns",
       subtitle = "Donations of Professors Employed by Harvard University",
       x = "Presidential  Campaigns",
       y = "Number of Individual Donations")

############################

num_donors <- profs %>%
  group_by(committee_name, contributor_name) %>%
  slice(1) %>%
  ungroup() %>%
  group_by(committee_name) %>%
  summarise(num_donors = n())

ggplot(num_donors, aes(x = reorder(committee_name, num_donors), y = num_donors, fill = committee_name)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") +
  labs(title = "Harvard Political Donors to 2020 Presidential Campaigns",
       subtitle = "Donations of Professors Employed by Harvard University",
       x = "Presidential Campaigns",
       y = "Number of Donors")

############################

amount_graph <- profs %>%
  group_by(committee_name) %>%
  summarise(total_donations = sum(contribution_receipt_amount)) %>%
  mutate(total_donations = as.numeric(total_donations))

ggplot(amount_graph, aes(x = reorder(committee_name, total_donations), y = total_donations, fill = committee_name)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") +
  labs(title = "Harvard Professors' Total Donations to 2020 Presidential Campaigns",
       subtitle = "Donations of Professors Employed by Harvard University",
       x = "Presidential Campaigns",
       y = "Dollars")

```

```{r Number of Donations}


number_donations <- data %>%
  group_by(committee_name) %>%
  summarise(num_donations = n()) %>%
  mutate(num_donations = as.numeric(num_donations))


ggplot(number_donations, aes(x = reorder(committee_name, num_donations), y = num_donations, fill = committee_name)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") + 
  labs(title = "Harvard Political Donations to 2020 Presidential Campaigns",
       subtitle = "Donations of Individuals Employed by Harvard University",
       x = "Presidential  Campaigns",
       y = "Number of Individual Donations")

```


```{r Presidential Unique Donors}

num_donors <- data %>%
  distinct(committee_name, contributor_name) %>%
  group_by(committee_name) %>%
  summarise(num_donors = n())

ggplot(num_donors, aes(x = reorder(committee_name, num_donors), y = num_donors, fill = committee_name)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") +
  labs(title = "Harvard Political Donors to 2020 Presidential Campaigns",
       subtitle = "Individuals Employed by Harvard University",
       x = "Presidential Campaigns",
       y = "Number of Donors")

```

```{r Presidential Amount Donated}

amount_graph <- data %>%
  group_by(committee_name) %>%
  summarise(total_donations = sum(contribution_receipt_amount)) %>%
  mutate(total_donations = as.numeric(total_donations))

ggplot(amount_graph, aes(x = reorder(committee_name, total_donations), y = total_donations, fill = committee_name)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") +
  labs(title = "Harvard Employees' Total Donations to 2020 Presidential Campaigns",
       subtitle = "Donations by Individuals Employed by Harvard University",
       x = "Presidential Campaigns",
       y = "Dollars")

```

```{r Presidential Mean Donation}

amount_graph <- data %>%
  group_by(committee_name) %>%
  summarise(mean_donations = mean(contribution_receipt_amount)) %>%
  mutate(mean_donations = as.numeric(mean_donations))

ggplot(amount_graph, aes(x = reorder(committee_name, mean_donations), y = mean_donations, fill = committee_name)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") +
  labs(title = "Harvard Employees' Mean Donations to 2020 Presidential Campaigns",
       subtitle = "Donations by Individuals Employed by Harvard University",
       x = "Presidential Campaigns",
       y = "Dollars")

```

```{r Presidential By Employer}

by_employer <- data %>%
  filter(contributor_employer == "HARVARD KENNEDY SCHOOL"  | 
           contributor_employer == "HARVARD LAW SCHOOL" | 
           contributor_employer == "HARVARD BUSINESS SCHOOL" | 
           contributor_employer == "HARVARD SCHOOL OF PUBLIC HEALTH" |
           contributor_employer == "HARVARD GRADUATE SCHOOL OF ARTS AND SCIENCES" |
           contributor_employer == "HARVARD GRADUATE SCHOOL OF EDUCATION" |
           contributor_employer == "HARVARD DIVINITY SCHOOL")

by_employer_sum <- by_employer %>%  
  group_by(contributor_employer) %>%
  summarise(total_donations = sum(contribution_receipt_amount)) %>%
  mutate(total_donations = as.numeric(total_donations))

ggplot(by_employer_sum, aes(x = reorder(contributor_employer, total_donations), y = total_donations, fill = contributor_employer)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") +
  labs(title = "Harvard Grad School Employees' Total Donations to 2020 Pres. Campaigns",
       subtitle = "Donations by Individuals Employed by Graduate Schools",
       x = "Graduate Schools",
       y = "Dollars")

by_employer_mean <- by_employer %>%  
  group_by(contributor_employer) %>%
  summarise(total_donations = mean(contribution_receipt_amount)) %>%
  mutate(total_donations = as.numeric(total_donations))

ggplot(by_employer_mean, aes(x = reorder(contributor_employer, total_donations), y = total_donations, fill = contributor_employer)) +
  geom_col() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") +
  labs(title = "Harvard Grad School Employees' Mean Donations to 2020 Pres. Campaigns",
       subtitle = "Donations by Individuals Employed by Graduate Schools",
       x = "Graduate Schools",
       y = "Dollars")
```

```{r Presidential Faceted by Employer}

by_employer_facet <- data %>%
  filter(contributor_employer == "HARVARD KENNEDY SCHOOL"  | 
           contributor_employer == "HARVARD LAW SCHOOL" | 
           contributor_employer == "HARVARD BUSINESS SCHOOL" | 
           contributor_employer == "HARVARD SCHOOL OF PUBLIC HEALTH" |
           contributor_employer == "HARVARD GRADUATE SCHOOL OF EDUCATION")

ggplot(by_employer_facet, aes(x = committee_name, fill = committee_name)) +
  geom_bar() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  theme(legend.position = "none") + 
  facet_wrap(~ contributor_employer) +
  labs(y = "Number of Donations",
       x = "Candidate")

employer_piechart <- by_employer_facet %>%
  group_by(contributor_employer) %>%
  summarise(num_donors = n()) 

#ggplot(employer_piechart, aes(x = "",y = num_donors, fill = contributor_employer)) +
#  geom_bar(stat="identity", width=1) + 
#  coord_polar("y", start=0)

#employer_piechart_money <- by_employer_facet %>%
#  group_by(contributor_employer) %>%
#  summarise(money = sum(contribution_receipt_amount)) %>%

#ggplot(employer_piechart_money, aes(x = "", y = money, fill = contributor_employer)) +
#  geom_bar(stat="identity", width=1) + 
#  coord_polar("y", start=0)


```

```{r Republican Vs Dem Support}

party_support <- data %>%
  #filter(party_full == "")
  group_by(party_full) %>%
  summarise(num_party = n())

ggplot(party_support, aes(x="", y=num_party, fill=party_full))+
  geom_bar(width = 1, stat = "identity")+
  coord_polar("y", start=0)+
  theme(axis.text.x=element_blank())  +
  geom_text(aes(y = num_party/2 + c(0, cumsum(num_party)[-length(num_party)]), 
            label = percent(num_party/100)), size=5)
  

```

```{r}

lm(data = data, contribution_receipt_amount ~ estimate)

ggplot(data, aes(x = estimate, y = contribution_receipt_amount))+
  scale_y_log10()+
  geom_jitter() + 
  geom_smooth(method = "lm") +
  labs(title = "Relationship Between Donation Size and Politican Ideology",
      x = "Estimated Political Ideology",
      y = "Donation Amount")

```

```{r donation size to total size}

ggplot(data, aes(x = receipts, y = contribution_receipt_amount))+
  scale_y_log10()+
  geom_jitter() + 
  geom_smooth(method = "lm") +
  #geom_smooth(method = "glm", method.args = list(family = "binomaial"), se = FALSE)+
  labs(title = "Relationship Between Donation Size and Campaign Total Donations",
      x = "Total Campaign Donation Receipts",
      y = "Donation Amount")


```

```{r num donors to total size}

donor_to_size <- data %>%
  group_by(committee_name) %>%
  mutate(num_donors = n()) %>%
  slice(1) %>%
  ungroup()

ggplot(donor_to_size, aes(x = receipts, y = num_donors))+
  scale_y_log10()+
  geom_jitter() + 
  geom_smooth(method = "lm") +
  labs(title = "Relationship Between Number of Donors and Campaign Total Donations",
      x = "Total Campaign Donation Receipts",
      y = "Number of Donors")

```

```{r}

data %>%
  group_by(committee_name) %>%
  mutate(num_donations = n()) %>%
  filter(num_donations > 20) %>%
  ggplot(aes(x = committee_name, y = contribution_receipt_amount))+
  theme(axis.text.x = element_text(angle = 90)) + 
  scale_y_log10()+
  geom_boxplot()

```





